const buses = [
  {
    id: "BUS1001",
    operatorName: "Orange Travels",
    busName: "Orange A/C Sleeper (2+1)",
    busType: "AC Sleeper",
    rating: 4.6,
    totalSeats: 40,
    availableSeats: 12,
    fare: { baseFare: 1299, serviceCharge: 50, totalFare: 1349 },
    route: { from: "Hyderabad", to: "Bangalore", distance: "570 km", duration: "9h 30m" },
    timings: { departure: "2025-10-13T21:30:00", arrival: "2025-10-14T06:45:00" },
    boardingPoints: ["Madhapur - 8:30 PM", "Gachibowli - 8:50 PM", "Mehdipatnam - 9:15 PM"],
    droppingPoints: ["Madiwala - 6:30 AM", "Silk Board - 6:45 AM"],
    amenities: ["Water Bottle", "Charging Point", "Blanket", "Reading Light", "WiFi"],
    busImage: "https://example.com/orange-travels.jpg"
  },
  {
    id: "BUS1002",
    operatorName: "VRL Travels",
    busName: "VRL Volvo Multi Axle Sleeper",
    busType: "Volvo Sleeper",
    rating: 4.8,
    totalSeats: 44,
    availableSeats: 7,
    fare: { baseFare: 1499, serviceCharge: 60, totalFare: 1559 },
    route: { from: "Hyderabad", to: "Chennai", distance: "630 km", duration: "10h 15m" },
    timings: { departure: "2025-10-13T20:45:00", arrival: "2025-10-14T07:00:00" },
    boardingPoints: ["Ameerpet - 8:00 PM", "Lakdikapul - 8:30 PM", "Kukatpally - 8:50 PM"],
    droppingPoints: ["Koyambedu - 6:45 AM", "Guindy - 7:00 AM"],
    amenities: ["WiFi", "Water Bottle", "Blanket", "CCTV", "Movie"],
    busImage: "https://example.com/vrl-travels.jpg"
  },
  {
    id: "BUS1003",
    operatorName: "TSRTC",
    busName: "TSRTC Super Luxury",
    busType: "Non-AC Seater",
    rating: 4.2,
    totalSeats: 50,
    availableSeats: 20,
    fare: { baseFare: 699, serviceCharge: 20, totalFare: 719 },
    route: { from: "Hyderabad", to: "Vijayawada", distance: "280 km", duration: "5h 30m" },
    timings: { departure: "2025-10-13T22:15:00", arrival: "2025-10-14T03:45:00" },
    boardingPoints: ["Miyapur - 9:30 PM", "LB Nagar - 10:00 PM"],
    droppingPoints: ["Benz Circle - 3:30 AM", "Ramavarappadu - 3:45 AM"],
    amenities: ["Water Bottle", "Charging Point", "Reading Light"],
    busImage: "https://example.com/tsrtc-bus.jpg"
  },
  {
    id: "BUS1004",
    operatorName: "SRS Travels",
    busName: "SRS Mercedes Benz Sleeper",
    busType: "AC Sleeper",
    rating: 4.7,
    totalSeats: 38,
    availableSeats: 9,
    fare: { baseFare: 1599, serviceCharge: 80, totalFare: 1679 },
    route: { from: "Bangalore", to: "Goa", distance: "560 km", duration: "9h 15m" },
    timings: { departure: "2025-10-13T20:30:00", arrival: "2025-10-14T05:45:00" },
    boardingPoints: ["Madiwala - 8:00 PM", "Majestic - 8:20 PM"],
    droppingPoints: ["Panaji - 5:30 AM", "Margao - 5:45 AM"],
    amenities: ["WiFi", "Charging Point", "Blanket", "Movie", "Reading Light"],
    busImage: "https://example.com/srs-bus.jpg"
  },
  {
    id: "BUS1005",
    operatorName: "Kaveri Travels",
    busName: "Kaveri A/C Sleeper (2+1)",
    busType: "AC Sleeper",
    rating: 4.5,
    totalSeats: 42,
    availableSeats: 5,
    fare: { baseFare: 1399, serviceCharge: 40, totalFare: 1439 },
    route: { from: "Chennai", to: "Bangalore", distance: "350 km", duration: "6h 45m" },
    timings: { departure: "2025-10-13T23:00:00", arrival: "2025-10-14T05:45:00" },
    boardingPoints: ["Koyambedu - 10:30 PM", "Perungalathur - 11:00 PM"],
    droppingPoints: ["Silk Board - 5:30 AM", "Madiwala - 5:45 AM"],
    amenities: ["Water Bottle", "Blanket", "Charging Point"],
    busImage: "https://example.com/kaveri-travels.jpg"
  },
  {
    id: "BUS1006",
    operatorName: "GreenLine Travels",
    busName: "GreenLine Scania Multi Axle",
    busType: "AC Seater",
    rating: 4.4,
    totalSeats: 48,
    availableSeats: 18,
    fare: { baseFare: 1099, serviceCharge: 40, totalFare: 1139 },
    route: { from: "Bangalore", to: "Chennai", distance: "345 km", duration: "6h 30m" },
    timings: { departure: "2025-10-13T22:00:00", arrival: "2025-10-14T04:30:00" },
    boardingPoints: ["Madiwala - 9:15 PM", "Electronic City - 9:45 PM"],
    droppingPoints: ["Guindy - 4:15 AM", "Koyambedu - 4:30 AM"],
    amenities: ["WiFi", "Charging Point", "Reading Light", "Movie"],
    busImage: "https://example.com/greenline-bus.jpg"
  },
  {
    id: "BUS1007",
    operatorName: "Morning Star Travels",
    busName: "Morning Star A/C Sleeper",
    busType: "AC Sleeper",
    rating: 4.3,
    totalSeats: 40,
    availableSeats: 14,
    fare: { baseFare: 1199, serviceCharge: 35, totalFare: 1234 },
    route: { from: "Hyderabad", to: "Pune", distance: "560 km", duration: "9h 10m" },
    timings: { departure: "2025-10-13T21:45:00", arrival: "2025-10-14T06:55:00" },
    boardingPoints: ["KPHB - 8:45 PM", "Ameerpet - 9:15 PM"],
    droppingPoints: ["Shivajinagar - 6:30 AM", "Swargate - 6:55 AM"],
    amenities: ["WiFi", "Water Bottle", "Blanket", "Charging Point"],
    busImage: "https://example.com/morningstar-bus.jpg"
  },
  {
    id: "BUS1008",
    operatorName: "National Travels",
    busName: "National Non-AC Seater",
    busType: "Non-AC Seater",
    rating: 4.0,
    totalSeats: 50,
    availableSeats: 25,
    fare: { baseFare: 599, serviceCharge: 20, totalFare: 619 },
    route: { from: "Bangalore", to: "Mysore", distance: "145 km", duration: "3h 15m" },
    timings: { departure: "2025-10-13T18:00:00", arrival: "2025-10-13T21:15:00" },
    boardingPoints: ["Majestic - 5:30 PM", "Madiwala - 5:50 PM"],
    droppingPoints: ["Mysore Bus Stand - 9:15 PM"],
    amenities: ["Reading Light", "Charging Point"],
    busImage: "https://example.com/national-bus.jpg"
  },
  {
    id: "BUS1009",
    operatorName: "Parveen Travels",
    busName: "Parveen A/C Sleeper (2+1)",
    busType: "AC Sleeper",
    rating: 4.6,
    totalSeats: 36,
    availableSeats: 10,
    fare: { baseFare: 1299, serviceCharge: 50, totalFare: 1349 },
    route: { from: "Chennai", to: "Coimbatore", distance: "510 km", duration: "8h 30m" },
    timings: { departure: "2025-10-13T22:15:00", arrival: "2025-10-14T06:45:00" },
    boardingPoints: ["Koyambedu - 9:30 PM", "Perungalathur - 10:15 PM"],
    droppingPoints: ["Gandhipuram - 6:30 AM", "Peelamedu - 6:45 AM"],
    amenities: ["WiFi", "Blanket", "Charging Point", "Reading Light"],
    busImage: "https://example.com/parveen-travels.jpg"
  },
  {
    id: "BUS1010",
    operatorName: "Rajesh Travels",
    busName: "Rajesh A/C Semi Sleeper",
    busType: "AC Semi Sleeper",
    rating: 4.1,
    totalSeats: 44,
    availableSeats: 15,
    fare: { baseFare: 999, serviceCharge: 30, totalFare: 1029 },
    route: { from: "Bangalore", to: "Hyderabad", distance: "570 km", duration: "9h 10m" },
    timings: { departure: "2025-10-13T21:00:00", arrival: "2025-10-14T06:10:00" },
    boardingPoints: ["Madiwala - 8:30 PM", "Hebbal - 9:00 PM"],
    droppingPoints: ["Miyapur - 6:00 AM", "Ameerpet - 6:10 AM"],
    amenities: ["Water Bottle", "Charging Point", "WiFi"],
    busImage: "https://example.com/rajesh-travels.jpg"
  },
  {
    id: "BUS1011",
    operatorName: "ABT X Travels",
    busName: "ABT A/C Sleeper",
    busType: "AC Sleeper",
    rating: 4.7,
    totalSeats: 40,
    availableSeats: 6,
    fare: { baseFare: 1599, serviceCharge: 50, totalFare: 1649 },
    route: { from: "Chennai", to: "Madurai", distance: "460 km", duration: "7h 45m" },
    timings: { departure: "2025-10-13T22:00:00", arrival: "2025-10-14T05:45:00" },
    boardingPoints: ["Koyambedu - 9:15 PM", "Tambaram - 9:45 PM"],
    droppingPoints: ["Mattuthavani - 5:30 AM", "Periyar - 5:45 AM"],
    amenities: ["WiFi", "Blanket", "Charging Point", "Movie"],
    busImage: "https://example.com/abt-travels.jpg"
  },
  {
    id: "BUS1012",
    operatorName: "Orange Travels",
    busName: "Orange A/C Seater Cum Sleeper",
    busType: "AC Seater Sleeper",
    rating: 4.5,
    totalSeats: 44,
    availableSeats: 11,
    fare: { baseFare: 1299, serviceCharge: 45, totalFare: 1344 },
    route: { from: "Hyderabad", to: "Vizag", distance: "620 km", duration: "11h 15m" },
    timings: { departure: "2025-10-13T19:30:00", arrival: "2025-10-14T06:45:00" },
    boardingPoints: ["Miyapur - 7:00 PM", "Kukatpally - 7:15 PM"],
    droppingPoints: ["RTC Complex - 6:30 AM"],
    amenities: ["Water Bottle", "WiFi", "Charging Point", "Blanket"],
    busImage: "https://example.com/orange-vizag.jpg"
  },
  {
    id: "BUS1013",
    operatorName: "Kesineni Travels",
    busName: "Kesineni Volvo Multi Axle Sleeper",
    busType: "Volvo Sleeper",
    rating: 4.9,
    totalSeats: 38,
    availableSeats: 4,
    fare: { baseFare: 1699, serviceCharge: 70, totalFare: 1769 },
    route: { from: "Hyderabad", to: "Mumbai", distance: "720 km", duration: "12h 30m" },
    timings: { departure: "2025-10-13T19:00:00", arrival: "2025-10-14T07:30:00" },
    boardingPoints: ["Ameerpet - 6:30 PM", "Madhapur - 6:45 PM"],
    droppingPoints: ["Dadar - 7:15 AM", "Borivali - 7:30 AM"],
    amenities: ["WiFi", "Blanket", "Charging Point", "Movie", "Reading Light"],
    busImage: "https://example.com/kesineni-bus.jpg"
  },
  {
    id: "BUS1014",
    operatorName: "SRM Travels",
    busName: "SRM A/C Sleeper",
    busType: "AC Sleeper",
    rating: 4.4,
    totalSeats: 40,
    availableSeats: 8,
    fare: { baseFare: 1399, serviceCharge: 50, totalFare: 1449 },
    route: { from: "Chennai", to: "Trichy", distance: "330 km", duration: "5h 45m" },
    timings: { departure: "2025-10-13T23:15:00", arrival: "2025-10-14T05:00:00" },
    boardingPoints: ["Perungalathur - 10:45 PM"],
    droppingPoints: ["Central Bus Stand - 5:00 AM"],
    amenities: ["WiFi", "Blanket", "Water Bottle"],
    busImage: "https://example.com/srm-bus.jpg"
  },
  {
    id: "BUS1015",
    operatorName: "Paulo Travels",
    busName: "Paulo Volvo Sleeper",
    busType: "Volvo Sleeper",
    rating: 4.6,
    totalSeats: 36,
    availableSeats: 9,
    fare: { baseFare: 1799, serviceCharge: 90, totalFare: 1889 },
    route: { from: "Goa", to: "Mumbai", distance: "580 km", duration: "10h 15m" },
    timings: { departure: "2025-10-13T20:00:00", arrival: "2025-10-14T06:15:00" },
    boardingPoints: ["Panaji - 7:30 PM", "Mapusa - 7:50 PM"],
    droppingPoints: ["Bandra - 6:00 AM", "Borivali - 6:15 AM"],
    amenities: ["Blanket", "Charging Point", "WiFi", "Movie"],
    busImage: "https://example.com/paulo-bus.jpg"
  },
  {
    id: "BUS1016",
    operatorName: "KPN Travels",
    busName: "KPN Non-AC Sleeper",
    busType: "Non-AC Sleeper",
    rating: 4.1,
    totalSeats: 40,
    availableSeats: 17,
    fare: { baseFare: 899, serviceCharge: 30, totalFare: 929 },
    route: { from: "Coimbatore", to: "Bangalore", distance: "365 km", duration: "7h 00m" },
    timings: { departure: "2025-10-13T23:00:00", arrival: "2025-10-14T06:00:00" },
    boardingPoints: ["Gandhipuram - 10:30 PM"],
    droppingPoints: ["Madiwala - 6:00 AM"],
    amenities: ["Reading Light", "Charging Point", "Water Bottle"],
    busImage: "https://example.com/kpn-bus.jpg"
  },
  {
    id: "BUS1017",
    operatorName: "VRL Travels",
    busName: "VRL Executive AC Seater",
    busType: "AC Seater",
    rating: 4.5,
    totalSeats: 46,
    availableSeats: 19,
    fare: { baseFare: 1299, serviceCharge: 50, totalFare: 1349 },
    route: { from: "Pune", to: "Bangalore", distance: "830 km", duration: "13h 00m" },
    timings: { departure: "2025-10-13T19:30:00", arrival: "2025-10-14T08:30:00" },
    boardingPoints: ["Swargate - 7:00 PM", "Katraj - 7:30 PM"],
    droppingPoints: ["Madiwala - 8:15 AM"],
    amenities: ["WiFi", "Charging Point", "Reading Light"],
    busImage: "https://example.com/vrl-pune-bus.jpg"
  },
  {
    id: "BUS1018",
    operatorName: "Kaleswari Travels",
    busName: "Kaleswari A/C Sleeper",
    busType: "AC Sleeper",
    rating: 4.3,
    totalSeats: 42,
    availableSeats: 10,
    fare: { baseFare: 1249, serviceCharge: 50, totalFare: 1299 },
    route: { from: "Vijayawada", to: "Hyderabad", distance: "280 km", duration: "5h 30m" },
    timings: { departure: "2025-10-13T22:30:00", arrival: "2025-10-14T04:00:00" },
    boardingPoints: ["Benz Circle - 10:00 PM"],
    droppingPoints: ["Miyapur - 4:00 AM"],
    amenities: ["Water Bottle", "Blanket", "Charging Point"],
    busImage: "https://example.com/kaleswari-bus.jpg"
  },
  {
    id: "BUS1019",
    operatorName: "Prasanna Travels",
    busName: "Prasanna Non-AC Seater",
    busType: "Non-AC Seater",
    rating: 4.0,
    totalSeats: 50,
    availableSeats: 22,
    fare: { baseFare: 649, serviceCharge: 25, totalFare: 674 },
    route: { from: "Pune", to: "Mumbai", distance: "150 km", duration: "3h 45m" },
    timings: { departure: "2025-10-13T17:00:00", arrival: "2025-10-13T20:45:00" },
    boardingPoints: ["Shivajinagar - 4:30 PM"],
    droppingPoints: ["Dadar - 8:45 PM"],
    amenities: ["Reading Light", "Charging Point"],
    busImage: "https://example.com/prasanna-bus.jpg"
  },
  {
    id: "BUS1020",
    operatorName: "Rajahamsa Travels",
    busName: "Rajahamsa A/C Sleeper",
    busType: "AC Sleeper",
    rating: 4.4,
    totalSeats: 40,
    availableSeats: 11,
    fare: { baseFare: 1349, serviceCharge: 45, totalFare: 1394 },
    route: { from: "Bangalore", to: "Hyderabad", distance: "570 km", duration: "9h 10m" },
    timings: { departure: "2025-10-13T22:15:00", arrival: "2025-10-14T07:25:00" },
    boardingPoints: ["Madiwala - 9:45 PM", "Hebbal - 10:15 PM"],
    droppingPoints: ["Ameerpet - 7:15 AM", "Miyapur - 7:25 AM"],
    amenities: ["WiFi", "Charging Point", "Blanket"],
    busImage: "https://example.com/rajahamsa-bus.jpg"
  }
];

export default buses;


// Export 
    // -  Named Export 
    // -  Default Export
